window.SONO_CONTENT={
  assessment:[
    {id:'sleepOnset',title:'Como costuma ser para adormecer?',type:'single',options:[['easy','Geralmente adormeço sem grande dificuldade'],['sometimes','Às vezes demoro bastante'],['often','Frequentemente demoro bastante']]},
    {id:'awakenings',title:'E durante a noite?',type:'single',options:[['few','Costumo dormir de forma relativamente contínua'],['some','Tenho alguns despertares'],['many','Tenho despertares frequentes ou longos']]},
    {id:'regularity',title:'Seus horários são previsíveis?',type:'single',options:[['regular','Na maior parte dos dias, sim'],['variable','Variam bastante'],['veryVariable','Mudam muito de um dia para outro']]},
    {id:'daytime',title:'Como o sono repercute no seu dia?',type:'single',options:[['low','Pouco impacto'],['moderate','Algum cansaço, irritação ou queda de rendimento'],['high','Impacto importante no funcionamento']]},
    {id:'worry',title:'Quanto você se preocupa com o sono?',type:'single',options:[['low','Pouco'],['moderate','Às vezes fico preocupado'],['high','Penso muito nisso e tento controlar o sono']]},
    {id:'lateCaffeine',title:'Cafeína costuma entrar no fim da tarde ou à noite?',type:'single',options:[['no','Raramente'],['sometimes','Às vezes'],['yes','Frequentemente']]},
    {id:'naps',title:'Como são os cochilos?',type:'single',options:[['none','Não costumo cochilar'],['short','Ocasionalmente ou por pouco tempo'],['frequent','Cochilo com frequência ou por períodos longos']]},
    {id:'breathing',title:'Há sinais respiratórios durante o sono?',subtitle:'Considere ronco intenso, pausas percebidas, engasgos ou sensação de sufocamento.',type:'single',options:[['no','Não percebo esses sinais'],['unsure','Não sei'],['yes','Sim, um ou mais desses sinais']]},
    {id:'sleepiness',title:'Você chega a cochilar involuntariamente em situações de risco?',subtitle:'Por exemplo, dirigindo ou operando equipamentos.',type:'single',options:[['no','Não'],['unsure','Não tenho certeza'],['yes','Sim']]},
    {id:'shift',title:'Seu trabalho muda seus horários de sono?',type:'single',options:[['no','Não'],['sometimes','Às vezes'],['yes','Sim, trabalho em turnos/plantões']]}
  ],
  modules:[
    {id:1,title:'Entenda seu sono',meta:'Fundamentos • 4 min',summary:'Pressão de sono, ritmo circadiano e por que o sono não responde bem à força de vontade.',understand:'O sono depende de processos biológicos que se acumulam e se sincronizam ao longo do dia. Um deles é a pressão de sono: quanto mais tempo acordado, maior tende a ser a propensão para dormir. Outro é o ritmo circadiano, que organiza períodos de maior alerta e maior propensão ao sono. Isso ajuda a entender por que “tentar muito” não cria sono sob comando.',experiment:'Hoje, observe duas coisas sem tentar corrigi-las: em que horário a sonolência aparece naturalmente e em que horário você realmente se levanta.',observe:'Seu horário de levantar costuma ser previsível ou muda conforme a noite anterior?',takeaway:'Sono é um processo regulado. O objetivo não é controlar cada minuto, mas criar condições mais coerentes para o sistema funcionar.',audio:'module1'},
    {id:2,title:'Descubra seu padrão',meta:'Observação • 4 min',summary:'Use o diário para enxergar tendências sem transformar números em nota.',understand:'Uma noite ruim chama muita atenção, mas não representa sozinha seu padrão. O diário organiza estimativas simples ao longo de vários dias e permite olhar regularidade, tempo na cama, despertares e funcionamento diurno. O valor está na tendência, não na precisão laboratorial de cada minuto.',experiment:'Faça registros por alguns dias e procure apenas uma tendência. Não tente explicar tudo de uma vez.',observe:'Depois de uma noite ruim, você costuma antecipar a hora de deitar, dormir até mais tarde ou cochilar para compensar?',takeaway:'Registrar serve para investigar, não para fiscalizar o sono.',audio:'module2'},
    {id:3,title:'Por que o sono pode continuar ruim?',meta:'Modelo 3P • 5 min',summary:'Diferencie o que iniciou o problema do que pode estar mantendo o problema hoje.',understand:'Algumas pessoas têm maior vulnerabilidade para dormir mal em certos contextos. Um evento pode precipitar o problema — estresse, doença, perda ou mudança de rotina. Depois, respostas compreensíveis podem perpetuar a dificuldade: passar mais tempo na cama, monitorar o relógio, cancelar atividades, cochilar ou tentar forçar o sono. O evento inicial pode passar, enquanto o sistema criado ao redor dele permanece.',experiment:'Escolha um comportamento que apareceu depois que seu sono piorou. Pergunte: isso ajuda apenas no curto prazo ou também melhora o padrão ao longo dos dias?',observe:'O que você começou a fazer para “compensar” o sono que talvez esteja mantendo sua atenção presa nele?',takeaway:'Entender o que mantém o problema hoje costuma ser mais útil do que procurar indefinidamente uma única causa original.',audio:'module3'},
    {id:4,title:'Cama e sono juntos novamente',meta:'Associação • 5 min',summary:'Entenda como vigília, preocupação e esforço podem ficar associados à cama.',understand:'Quando a cama vira lugar de preocupação, celular, trabalho, frustração e tentativas prolongadas de dormir, o cérebro pode aprender uma associação indesejada entre cama e vigília. Estratégias de controle de estímulos procuram reconstruir a cama como sinal de sono, sem transformar isso em regra punitiva.',experiment:'Observe o que costuma acontecer quando você percebe que está acordado e frustrado na cama. Só registre a sequência: pensamento, emoção e comportamento.',observe:'Sua cama hoje está mais associada a descanso ou a monitoramento e esforço?',takeaway:'A meta não é obedecer uma regra perfeita. É reduzir o tempo em que a cama se torna palco de luta com o sono.',audio:'module4'},
    {id:5,title:'Tempo na cama e consolidação',meta:'Regularidade • 5 min',summary:'Mais tempo disponível para dormir nem sempre significa mais sono.',understand:'Depois de noites ruins, é comum ampliar o tempo na cama para tentar recuperar o sono. Em algumas pessoas isso aumenta a oportunidade de ficar acordado na própria cama e torna o sono mais fragmentado. Em TCC-I, ajustes de tempo na cama podem ser úteis, mas precisam ser individualizados e respeitar critérios de segurança.',experiment:'Sem reduzir seu tempo na cama por conta própria, observe por alguns dias a diferença entre “tempo na cama” e “tempo realmente dormindo”.',observe:'Você costuma deitar muito mais cedo ou levantar muito mais tarde depois de uma noite ruim?',takeaway:'Regularidade e coerência importam mais do que perseguir uma quantidade perfeita de horas.',audio:'module5'},
    {id:6,title:'Quando a cabeça não desliga',meta:'Cognições • 5 min',summary:'Trabalhe preocupação, monitoramento e necessidade de controlar a noite.',understand:'Quanto mais o sono vira uma tarefa importante, mais fácil é monitorar sinais de fracasso: olhar o relógio, calcular horas restantes, prever um dia terrível e testar se o corpo já está sonolento. Esse monitoramento aumenta saliência e ameaça. O trabalho cognitivo não consiste em “pensar positivo”, mas em responder de forma mais flexível às previsões e à urgência.',experiment:'Quando surgir “preciso dormir agora”, acrescente: “meu trabalho é reduzir a luta; o sono não precisa ser produzido por força”.',observe:'Qual pensamento aparece com mais frequência quando você percebe que ainda está acordado?',takeaway:'Reduzir urgência não significa desistir do sono. Significa retirar combustível do estado de alerta.',audio:'module6'},
    {id:7,title:'Desacelerar',meta:'Regulação • 5 min',summary:'Use respiração, relaxamento e atenção como ferramentas de redução de ativação.',understand:'Técnicas de desaceleração podem ajudar quando o corpo ou a mente estão muito ativados. Elas funcionam melhor quando não são usadas como teste obrigatório para “fazer o sono acontecer”. O objetivo é diminuir um pouco a ativação e permitir que o organismo retome seus próprios processos.',experiment:'Escolha um áudio curto e use-o como prática de desaceleração, sem checar durante o exercício se você já está ficando com sono.',observe:'Você consegue praticar relaxamento sem transformar a técnica em uma prova que precisa funcionar?',takeaway:'A prática é reduzir ativação. Dormir pode vir depois, mas não é uma ordem que você precisa cumprir.',audio:'module7'},
    {id:8,title:'Meu sono daqui para frente',meta:'Manutenção • 4 min',summary:'Construa um plano flexível para noites boas, ruins e imprevisíveis.',understand:'Melhorar o sono não significa nunca mais ter uma noite ruim. Viagens, estresse, doença e mudanças de rotina podem produzir oscilações. O objetivo de manutenção é reconhecer essas oscilações sem reconstruir o ciclo de esforço, compensação e vigilância.',experiment:'Abra “Meu Plano de Sono” e escreva duas decisões: o que fazer quando a noite for difícil e o que evitar no dia seguinte.',observe:'Qual é o primeiro comportamento de compensação que você gostaria de perceber mais cedo?',takeaway:'Uma noite ruim é um evento. Ela não precisa virar uma nova estratégia de controle para a semana inteira.',audio:'module8'}
  ],
  tools:[
    {id:'mind',title:'Minha mente não desliga',desc:'Um exercício curto para reduzir urgência e deixar pensamentos passarem.',audio:'mind'},
    {id:'anxiety',title:'Estou ansioso',desc:'Atenção ao corpo e respiração sem exigir que a ansiedade desapareça.',audio:'anxiety'},
    {id:'awake',title:'Estou acordado há bastante tempo',desc:'Reduza a luta com o relógio e reorganize os próximos minutos.',audio:'awake'},
    {id:'middle',title:'Acordei no meio da noite',desc:'Uma orientação breve para não transformar o despertar em emergência.',audio:'middle'},
    {id:'frustrated',title:'Estou frustrado por não dormir',desc:'Descole seu valor e seu amanhã da necessidade de “vencer” a noite.',audio:'frustrated'},
    {id:'slow',title:'Preciso desacelerar',desc:'Uma prática de relaxamento progressivo e atenção corporal.',audio:'slow'}
  ],
  audios:{
    welcome:{title:'Bem-vindo ao Sono em Dia',category:'Apresentação',duration:'1–2 min',kind:'explain',script:'Talvez você tenha chegado aqui porque seu sono não está tão previsível quanto gostaria. Antes de qualquer técnica, uma ideia importante: dormir não é uma tarefa que você precisa executar perfeitamente. O sono é um processo biológico, influenciado por ritmo, tempo acordado, contexto, hábitos e também pela forma como reagimos às noites difíceis. Aqui, você vai observar padrões, experimentar mudanças pequenas e construir um plano que faça sentido para a sua realidade. Sem notas. Sem competição. Sem promessas de uma noite perfeita. Comece pelo seu mapa do sono ou, se já estiver acompanhando seus padrões, faça um registro curto pela manhã. O objetivo é simples: compreender melhor o seu sono para lidar com ele com menos esforço e mais clareza.'},
    module1:{title:'Como seu sono funciona',category:'Módulo 1',duration:'3 min',kind:'explain',script:'Existe uma diferença importante entre estar cansado e estar pronto para dormir. Ao longo do tempo em que permanecemos acordados, aumenta uma pressão biológica de sono. Ao mesmo tempo, o relógio circadiano organiza momentos de maior alerta e momentos de maior propensão ao sono. Esses dois processos interagem. É por isso que uma pessoa pode estar cansada e, ainda assim, sentir a mente muito desperta em determinado horário. Também explica por que o sono não responde bem a ordens. Quando você pensa “agora eu preciso dormir”, o corpo não recebe isso como um comando simples. Em algumas situações, a urgência aumenta monitoramento e ativação. Uma forma mais útil de começar é observar regularidade, exposição à luz, tempo acordado e os horários em que a sonolência aparece naturalmente. Seu trabalho não é fabricar sono. É organizar condições mais coerentes para que o sistema possa fazer o que sabe fazer.'},
    module2:{title:'Seu padrão é maior que uma noite',category:'Módulo 2',duration:'3 min',kind:'explain',script:'Depois de uma noite difícil, é comum acordar com a sensação de que tudo deu errado. A memória tende a destacar os períodos de vigília, especialmente quando você ficou preocupado ou olhando o relógio. Um diário simples ajuda a ampliar a perspectiva. Não porque ele descubra o minuto exato em que você dormiu. Isso não é necessário. O objetivo é perceber tendências ao longo de vários dias. Seus horários de levantar são parecidos? Você passa muito tempo na cama tentando compensar? Há despertares mais longos em alguns dias e menos em outros? Como fica sua energia durante o dia? Quando olhamos padrões, a pergunta deixa de ser “como faço para consertar esta noite?” e passa a ser “o que este conjunto de dias está me mostrando?”. Essa mudança reduz a pressão sobre uma noite isolada e produz informação mais útil para decisões.'},
    module3:{title:'O que mantém o problema hoje',category:'Módulo 3',duration:'3 min',kind:'explain',script:'Uma dificuldade de sono pode começar depois de uma fase de estresse, uma doença, uma perda ou uma mudança importante de rotina. Esse evento explica o início, mas nem sempre explica por que o problema continua meses depois. Quando o sono piora, fazemos coisas muito compreensíveis para tentar recuperar controle. Deitamos mais cedo. Ficamos mais tempo na cama. Cancelamos atividades. Cochilamos. Checamos o relógio. Procuramos sinais de sonolência. Criamos rituais cada vez mais rígidos. Algumas dessas respostas aliviam a ansiedade no curto prazo, mas podem manter atenção, vigília e irregularidade. A pergunta útil é: o que começou depois que meu sono piorou e continua acontecendo hoje? Não para encontrar culpa. Apenas para descobrir quais mecanismos ainda podem ser modificados.'},
    module4:{title:'Cama e sono: reconstruindo a associação',category:'Módulo 4',duration:'3 min',kind:'explain',script:'O cérebro aprende por associação. Se muitas noites passam a incluir preocupação, celular, trabalho, cálculos de horas restantes e longos períodos tentando dormir, a cama pode começar a sinalizar alerta em vez de descanso. Isso não acontece porque você fez algo errado. É aprendizagem. E aprendizagem pode ser reorganizada. Em TCC-I, estratégias de controle de estímulos procuram reduzir vigília condicionada e reconstruir a cama como contexto predominantemente ligado ao sono. O ponto importante é não transformar isso em outra regra rígida. Observe primeiro o que acontece quando você percebe que está acordado e frustrado. O que pensa? O que faz? Quanto tempo permanece tentando resolver a noite? Essa sequência mostra onde existe espaço para mudar a relação entre cama, vigília e esforço.'},
    module5:{title:'Mais tempo na cama não é sempre mais sono',category:'Módulo 5',duration:'3 min',kind:'explain',script:'Depois de dormir mal, parece lógico dar ao corpo mais oportunidade para dormir. Deitar mais cedo, levantar mais tarde ou passar mais tempo na cama pode parecer uma forma de recuperar a noite. Mas, para algumas pessoas com insônia, ampliar demais essa oportunidade aumenta justamente o tempo acordado na cama. O sono pode ficar mais fragmentado e a cama mais associada a vigília. Intervenções de TCC-I podem ajustar a oportunidade de sono, mas isso precisa ser feito com critério e segurança. Aqui, não vamos reduzir automaticamente o seu tempo na cama. Primeiro, observe a diferença entre tempo disponível e tempo realmente dormindo. Regularidade, contexto e funcionamento durante o dia importam. O objetivo não é perseguir uma quantidade perfeita de horas. É tornar o sistema mais previsível e consolidado.'},
    module6:{title:'Quando tentar dormir vira trabalho',category:'Módulo 6',duration:'3 min',kind:'explain',script:'Talvez você conheça esta sequência. Você percebe que ainda está acordado. Olha o horário. Calcula quantas horas restam. Imagina como estará amanhã. Começa a testar se o corpo já está relaxado. E então tenta ainda mais. O problema é que monitorar o sono dessa forma aumenta atenção e ameaça. A mente passa a tratar a noite como uma tarefa de alto risco. Trabalhar pensamentos não significa repetir frases positivas. Significa questionar a urgência e responder de forma mais flexível. Quando aparecer “eu preciso dormir agora”, experimente reconhecer: “eu gostaria de dormir, mas não preciso produzir o sono à força neste minuto”. Seu objetivo imediato pode ser apenas reduzir a luta. Esse pequeno deslocamento não garante sono. Ele apenas deixa de alimentar desnecessariamente o estado de alerta.'},
    module7:{title:'Desacelerar sem transformar em teste',category:'Módulo 7',duration:'3 min',kind:'calm',script:'Técnicas de respiração, relaxamento e atenção podem ser úteis quando seu corpo está muito ativado. Existe, porém, uma armadilha comum: usar cada técnica como um teste. “Se eu fizer isso corretamente, preciso dormir.” Quando esse pensamento aparece, a prática vira mais uma tarefa de desempenho. Hoje, tente outra proposta. Escolha uma técnica apenas para diminuir um pouco a ativação. Não verifique durante o exercício se o sono já chegou. Não precisa medir seu relaxamento. Apenas acompanhe a respiração, solte alguma tensão desnecessária e deixe alguns minutos passarem. Se o sono vier, tudo bem. Se não vier agora, a prática ainda pode ter cumprido seu papel: reduzir a luta e oferecer ao corpo uma condição mais tranquila.'},
    module8:{title:'Como responder a uma noite ruim',category:'Módulo 8',duration:'3 min',kind:'explain',script:'Melhorar o sono não significa eliminar todas as noites ruins. Pessoas que dormem bem também têm noites fragmentadas, períodos de estresse e mudanças de rotina. A diferença importante está no que acontece depois. Uma noite difícil pode virar um evento isolado ou pode iniciar uma sequência de compensações: deitar muito cedo, cancelar atividades, cochilar longamente, monitorar a noite seguinte e reconstruir a urgência. Um plano de manutenção ajuda você a decidir antes da próxima noite ruim como pretende responder. Quais comportamentos quer manter? O que não deseja exagerar? Quando buscar ajuda? Quanto mais previsível for sua resposta, menor a chance de uma única noite comandar toda a semana. Flexibilidade é parte do tratamento, não sinal de falha.'},
    mind:{title:'Minha mente não desliga',category:'Mente acelerada',duration:'3 min',kind:'calm',script:'Antes de tentar parar seus pensamentos, experimente uma coisa diferente. Não precisamos esvaziar sua mente. Pensamentos podem continuar aparecendo. Por alguns instantes, apenas perceba que existe um pensamento acontecendo. Talvez seja uma preocupação com amanhã. Talvez um cálculo de horas. Talvez uma lembrança. Em vez de entrar na discussão, nomeie silenciosamente: “minha mente está tentando resolver isso agora”. Faça uma expiração um pouco mais longa, sem forçar. E deixe o pensamento permanecer no fundo, sem precisar terminá-lo. Se outro vier, faça o mesmo. Não estamos buscando silêncio perfeito. Estamos reduzindo a obrigação de responder a tudo. Você pode voltar sua atenção ao contato do corpo com a cama, ao peso das pernas, ao movimento discreto da respiração. Nada precisa ser resolvido neste minuto.'},
    anxiety:{title:'Estou ansioso',category:'Regulação',duration:'4 min',kind:'calm',script:'Não precisamos fazer a ansiedade desaparecer. Vamos apenas diminuir um pouco a intensidade da resposta. Perceba onde seu corpo toca a superfície. Solte a mandíbula se ela estiver contraída. Deixe os ombros descerem o que for confortável. Agora inspire sem ampliar demais o ar. E solte um pouco mais devagar. Mais uma vez. Sem buscar uma respiração perfeita. Enquanto expira, observe se alguma parte do corpo consegue abandonar um pouco de esforço. Se a mente perguntar “isso está funcionando?”, reconheça a pergunta e volte ao corpo. O objetivo não é produzir sono. É mostrar ao sistema que, nos próximos minutos, você não precisa resolver nada. Continue em um ritmo confortável. Ansiedade pode estar presente e, ainda assim, você pode reduzir a luta com ela.'},
    awake:{title:'Estou acordado há bastante tempo',category:'Noite difícil',duration:'3 min',kind:'calm',script:'Estar acordado quando você queria dormir é frustrante. O primeiro impulso costuma ser calcular quanto tempo resta e tentar com mais força. Antes disso, reduza a escala do problema. Você não precisa resolver a noite inteira agora. Cuide apenas dos próximos minutos. Evite transformar o relógio em uma contagem regressiva. Pergunte a si mesmo: estou descansando de forma relativamente tranquila ou estou preso em esforço e frustração? Se a cama virou um lugar de luta, talvez seja útil interromper esse ciclo e fazer algo calmo em outro contexto até que a sonolência retorne, conforme a orientação que você estiver seguindo. Se você estiver confortável, apenas deixe o corpo repousar sem exigir sono imediato. A prioridade agora é reduzir vigília associada à urgência.'},
    middle:{title:'Acordei no meio da noite',category:'Noite difícil',duration:'3 min',kind:'calm',script:'Um despertar durante a noite não precisa virar uma emergência. O cérebro humano passa por mudanças de estágio e pequenos despertares podem ocorrer. O que costuma ampliar o problema é a sequência que vem depois: checar o horário, calcular o dia seguinte, acender muita luz, abrir conteúdos estimulantes ou começar a testar se o sono vai voltar. Se puder, mantenha a situação simples. Observe seu nível de sonolência. Reduza o contato com o relógio. Não negocie com o sono. Se estiver tranquilo, permita alguns minutos sem objetivo. Se estiver muito desperto e frustrado, use a estratégia combinada para sair do ciclo de vigília condicionada. O foco é não transformar um despertar em uma prova sobre como será o resto da noite.'},
    frustrated:{title:'Estou frustrado por não dormir',category:'Noite difícil',duration:'3 min',kind:'calm',script:'Faz sentido estar frustrado. Você queria dormir e isso não está acontecendo no ritmo desejado. Mas sua noite não precisa virar uma disputa. Tente separar duas coisas: a preferência de dormir agora e a obrigação de fazer isso acontecer. Você pode preferir muito o sono sem conseguir comandá-lo. Quando essa obrigação diminui, também diminui parte da vigilância. Amanhã pode ser um dia menos confortável, mas uma noite difícil não define sua capacidade inteira de funcionar. Por enquanto, abandone a tarefa de vencer a noite. Escolha apenas reduzir um pouco a tensão, a luz, os cálculos e a urgência. Seu valor e seu amanhã não dependem de atingir um número perfeito de horas.'},
    slow:{title:'Preciso desacelerar',category:'Relaxamento',duration:'5 min',kind:'calm',script:'Ajuste o corpo do jeito que estiver confortável. Você não precisa ficar completamente imóvel. Comece percebendo os pés. Sem mexer muito, note se existe alguma tensão que pode ser reduzida em dez por cento. Não precisamos zerar a tensão. Suba a atenção para as pernas. Deixe o peso delas ser sustentado pela superfície. Perceba o abdome se movendo com a respiração. Não puxe o ar. Apenas deixe a expiração terminar um pouco mais solta. Agora observe os ombros. Se estiverem elevados, permita que desçam o que for natural. Solte a língua do céu da boca. Afrouxe a mandíbula. A testa não precisa ficar perfeitamente lisa. Apenas menos ocupada. Se pensamentos aparecerem, eles podem ficar. Não estamos tentando expulsá-los. Volte ao peso do corpo, à expiração e às regiões que conseguem abandonar um pouco de esforço. Não há nada para concluir. Quando quiser, permaneça aqui sem acompanhar cada etapa.'}
  }
};
